language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
  - yarn build
deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on:
    branch: master
notifications:
  slack:
    rooms:
    - $SLACK_CHANNEL
  email:
    reciepients:
    - juniorjose.aguilarparra@gmail.com
    - $EMAIL_ADMIN
    on_success: always
    on_failure: always
# manda emails a esos mails cuando es exitoso y cuando falla
